

% TI Refinement
% -----------------------------

INCPCP_TI_REFINEMENT_STANDARD = 1;
INCPCP_TI_REFINEMENT_SEARCH   = 2;
INCPCP_TI_REFINEMENT_CSR      = 3;

INCPCP_TI_ROTATION_MOSAICPAD  = 4;
INCPCP_TI_ROTATION_ZEROPAD    = 5;

